runtime: nodejs
env: flex

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: /cloudsql/advstsys-lit:us-east1:advstsys-lit
  MYSQL_USER: root
  MYSQL_PASSWORD: abcde12345

beta_settings:
  cloud_sql_instances: advstsys-lit:us-east1:advstsys-lit
