# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: echo "foo bar"
      - run: yarn install
      - run: curl -o $HOME/google_appengine_1.9.30.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.30.zip
      - run: unzip -q -d $HOME $HOME/google_appengine_1.9.30.zip
      - run: echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
      - run: sed  s/YOUR-API-KEY/$API_KEY/ api_key.py.sample > api_key.py
      - run: mkdir -p lib
      - run: pip install -r requirements.txt -t lib
      - run: gcloud --quiet components update app
      - run: gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
      - run: gcloud config set project $GCLOUD_PROJECT

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
