# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: echo "foo bar"
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run:
          name: Install some stuff
          command: echo "deploy deploy deploy!"
      - run: curl -o $HOME/google_appengine_1.9.30.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.30.zip
      - run: unzip -q -d $HOME $HOME/google_appengine_1.9.30.zip
      # Retrieve our secrets from the CircleCI environment
      - run: echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/client-secret.json
      # - sed  s/YOUR-API-KEY/$API_KEY/ api_key.py.sample > api_key.py
      # vendor our dependencies
      - run: mkdir -p lib
      - run: curl -o $HOME/google-cloud-sdk.tgz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-182.0.0-linux-x86_64.tar.gz
      - run: tar -zxvf $HOME/google-cloud-sdk.tgz
      - run: google-cloud-sdk/bin/gcloud --quiet components update
      - run: google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run: google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT
      - run: yarn install
      - run: git clone https://github.com/5356-ct/lit.git
      - run: pwd
      - run: ls $HOME/lit/
      - run: google-cloud-sdk/bin/gcloud app deploy $HOME/lit/app.yaml


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
            

